#!/bin/sh

# GNU ls has -G
#

LS_OPTS='-h'

if ls --classify >& /dev/null; then
    LS_OPTS+=' --classify --color=auto'
fi

if ls -G >& /dev/null; then
    LS_OPTS+=' -G'
fi

# Any OS specific stuff here.
#if [[ "$(uname)" == "Darwin" ]]; then
    # OSX
#elif [[ "$(expr substr $(uname -s) 1 5)" == "SunOS" ]]; then
    # Solaris
#elif [[ "$(expr substr $(uname -s) 1 5)" == "Linux" ]]; then
    # Linux
#fi

alias ls="ls ${LS_OPTS}"

alias ll='ls -l'
alias la='ls -a'
alias lA='ls -A'

alias RM='rm -rf'

alias -- +x='chmod +x'
alias -- -x='chmod -x'
alias -- +r='chmod +r'
alias -- +rX-R='chmod +rX -R' # make dirs +rx, files +r

alias ..='cd ..'
alias ..1='cd ..'
alias ..2='cd ../..'
alias ..3='cd ../../..'
alias ..4='cd ../../../..'
alias ..5='cd ../../../../..'
alias ..6='cd ../../../../../..'
alias ..6='cd ../../../../../../..'
alias ..7='cd ../../../../../../../..'
alias ..8='cd ../../../../../../../../..'
alias ..9='cd ../../../../../../../../../..'

export QUOTING_STYLE=literal

